SELECT DISTINCT
	css.CSTS_DESCRIPTION,
	css.CSTS_LONG_DESCRIPTION
FROM
	CONF_STATION_STRUCTURES css
INNER JOIN SECU_PROF_ROLE_ACTIONS spra ON
	css.SIAC_ID = spra.SIAC_ID
INNER JOIN SECU_USERS su ON
	spra.PROF_ID = su.PROF_ID
INNER JOIN SECU_PROFESSIONAL_ROLES scr ON
	su.PROF_ID = scr.PROF_ID
WHERE
	su.USER_LOGIN = 'abernal'
	AND scr.USRO_FAVOURITE = 'true';